### ISSUE TITLE
Any plan to migrate this package to Laminas ?

### ISSUE THREAD

**Issue by vrkansagara** [phly/PhlyBlog#15]
hello, @weierophinney.  I would appreciate it if you can migrate this package as this package provide me some use case for static site generator kind of concept and this helps to keep`Laminas` is my first priority for development.

**Comment by vrkansagara** [comment]
Hello @weierophinney , I would more appreciative if you can migrate this package to Laminas. As I tried to migrate this package but somehow I can't, Awaiting for your response and `many thanks`  in advance.

**Comment by vrkansagara** [comment]
Hello @weierophinney  I don't wanted to bother you but is any plan to migrate this package to Laminas current version?

**Comment by rieschl** [comment]
At first glance, at least the following steps have to be done to be usable in a up-to-date `laminas-mvc` project:

- [ ] bump to PHP `7.x`. Probably `7.3` because of PHPUnit `9.3` (or `7.4` if it's not too much work to use typed properties). The [MVC skeleton v1.0.0](https://github.com/laminas/laminas-mvc-skeleton/releases/tag/1.0.0) requires PHP 7.3 so that's probably a reasonable choice
- [ ] upgrade to latest laminas packages

While at it, 
- [ ] add a proper LICENSE to repo and composer.json
- [ ] remove custom autoloaders

Is that okay? Probably pretty much the same has to be done in [PhlyCommon](https://github.com/phly/PhlyCommon).

Are you okay with that @weierophinney ?

**Comment by weierophinney** [comment]
@rieschl Yep, sounds good. I'll add the Hacktoberfest info to PhlyCommon as well; ping me on Slack or tag me in a comment so I see the issues/pull requests.

**Comment by vrkansagara** [comment]
@rieschl  I have done bellow task

-[x] add a proper LICENSE to repo and composer.json  using #18 and #17 
-[x]  remove custom autoloaders  using #18

**Comment by vrkansagara** [comment]
@rieschl  @weierophinney  #19 Is added for symfony-cli for command runner.

**Comment by vrkansagara** [comment]
@weierophinney  Ping for open PR.
