### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function compile() on null

### ISSUE THREAD

**Issue by vrkansagara** [phly/PhlyBlog#22]
I try to use this package with fresh installation of **laminas-mvc-skeleton** everything works perfect except this error @weierophinney  or @rieschl  Do you have any ides why **$listener** is not getting this **compile** method

![image](https://user-images.githubusercontent.com/12006483/95815574-968cb480-0d3a-11eb-853c-f0885ff9564c.png)

I tried to debug more on this and found that, While **entries by tag** is compiled at that time **$listener** become null.

![image](https://user-images.githubusercontent.com/12006483/95816117-f20b7200-0d3b-11eb-92b5-30acdd3e9237.png)

**Comment by rieschl** [comment]
There seems to be a typo in the Command. Give me a sec, I'll come up with a fix...

**Comment by weierophinney** [comment]
@rieschl I've got it, and will have a patch against the 2.0.x branch shortly.

**Comment by weierophinney** [comment]
Fixed with #23.

**Comment by rieschl** [comment]
@weierophinney That is only a part of the fix. Somehow lots of things got mixed up. For example, the [`getListeners`](https://github.com/phly/PhlyBlog/blob/2.1.x/src/Console/CompileCommand.php#L123) call has to be before [`$this->compiler->compile()`](https://github.com/phly/PhlyBlog/blob/2.1.x/src/Console/CompileCommand.php#L116) because `getListeners` _attaches_ the Listeners, otherwise they do nothing.

If I do that, it still does nothing, because the [`ViewFactory`](https://github.com/phly/PhlyBlog/blob/2.1.x/src/Console/ViewFactory.php#L21) adds the renderer, but because `View` is `EventManagerAwareInterface`, and there is no `SharedEventManager`, the Initializer in `laminas-mvc` [overrides the whole `EventManager`](https://github.com/laminas/laminas-mvc/blob/3.2.x/src/Service/ServiceManagerConfig.php#L104), thus removing the rendererStrategy.

If I set the `EventManager` in the `ViewFactory` (with `$view->setEventManager($container->get('EventManager'));`), the Renderer blows up because it wants the `ViewHelper\Url` helper but it's delegated to the factory in `laminas-mvc-console`, but the Application doesn't have a [`MvcEvent`](https://github.com/laminas/laminas-mvc-console/blob/master/src/Service/ConsoleViewHelperManagerDelegatorFactory.php#L96) there and generates a null pointer exception.

That's as far as I got at the moment. Stay tuned 🙃
