### ISSUE TITLE
blog file is not compiling with laminas-mvc-skeleton/tree/2.4.x

### ISSUE THREAD

**Issue by vrkansagara** [phly/PhlyBlog#35]
@weierophinney  I am trying to run this package using `https://github.com/laminas/laminas-mvc-skeleton/tree/2.4.x` it is not compiling files. Can you please look into this.

**Comment by vrkansagara** [comment]
@weierophinney is it possible for you to check this issue !

**Comment by weierophinney** [comment]
Nothing has changed in this repo in four years, so if it's an issue, it's not a new one.

At this time:

- I'm likely going to archive this and a number of other repos under this org, as they targeted early versions of Zend Framework 2/Laminas 2, and I did not update them along with the framework. I have no interest in doing so at this time, as I no longer use the MVC regularly.
- You have not provided information to allow me to reproduce the issue you see. What version of this library are you using? What version of Composer was used (some recent versions do not work with plugins we had before)? What dependencies were installed with it? What version of PHP? Can you provide samples of Markdown blog posts that are not compiling? I need a **reproducible sample** in order to even attempt to look at it; otherwise, I'm guessing blindly.

**Comment by vrkansagara** [comment]
(1) git clone https://github.com/laminas/laminas-mvc-skeleton.git
(2) composer require phly/phly-blog
(3) configure package 
(4) see it is not working due to code require to migrate ( phlycore and phlyblog)

PHP 8.2.15 (cli) (built: Jan 16 2024 12:19:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.15, Copyright (c), by Zend Technologies

**Comment by weierophinney** [comment]
What version of Composer? You'll likely need a v1 or no later than a v2.2 release, as plugins we used then no longer work with recent versions. 

Also, I have no intention of updating this to work directly with Laminas MVC without the bridge. If you need that, please fork.

**Comment by vrkansagara** [comment]
> aminas MVC without the bridge

noted with thanks. I will give it try in my fork to make it workable. again thanks for you quick response.
